SEARCH_MESSAGE = "Attendi, potrebbero volerci fino a 5 minuti (per interrompere la ricerca corrente utilizza il comando /stop)"
STOP_SEARCH_MESSAGE = "Ricerca interrotta"
ERROR_NICKNAME = "Nessun nickname specificato. Utilizza il comando come segue: /track nickname"
WARNING_MESSAGE = "Stai già facendo una ricerca. Attendi che finisca, prima di chiederne un'altra oppure utilizza il comando /stop per interrompere la ricerca corrente"
WELCOME_MESSAGE = "Benvenuto! Utilizza il comando /track <nickname> per iniziare la ricerca"
WARNING_NO_SEARCH_MESSAGE  = "Non stai facendo nessuna ricerca, al momento"